var ks = ["postMessage","blur","focus","close","frames","self","window","parent","opener","top","length","closed","location","document","origin","name","history","locationbar","menubar","personalbar","scrollbars","statusbar","toolbar","status","frameElement","navigator","customElements","external","screen","innerWidth","innerHeight","scrollX","pageXOffset","scrollY","pageYOffset","screenX","screenY","outerWidth","outerHeight","devicePixelRatio","clientInformation","screenLeft","screenTop","defaultStatus","defaultstatus","styleMedia","onanimationend","onanimationiteration","onanimationstart","onsearch","ontransitionend","onwebkitanimationend","onwebkitanimationiteration","onwebkitanimationstart","onwebkittransitionend","isSecureContext","onabort","onblur","oncancel","oncanplay","oncanplaythrough","onchange","onclick","onclose","oncontextmenu","oncuechange","ondblclick","ondrag","ondragend","ondragenter","ondragleave","ondragover","ondragstart","ondrop","ondurationchange","onemptied","onended","onerror","onfocus","oninput","oninvalid","onkeydown","onkeypress","onkeyup","onload","onloadeddata","onloadedmetadata","onloadstart","onmousedown","onmouseenter","onmouseleave","onmousemove","onmouseout","onmouseover","onmouseup","onmousewheel","onpause","onplay","onplaying","onprogress","onratechange","onreset","onresize","onscroll","onseeked","onseeking","onselect","onstalled","onsubmit","onsuspend","ontimeupdate","ontoggle","onvolumechange","onwaiting","onwheel","onauxclick","ongotpointercapture","onlostpointercapture","onpointerdown","onpointermove","onpointerup","onpointercancel","onpointerover","onpointerout","onpointerenter","onpointerleave","onafterprint","onbeforeprint","onbeforeunload","onhashchange","onlanguagechange","onmessage","onmessageerror","onoffline","ononline","onpagehide","onpageshow","onpopstate","onrejectionhandled","onstorage","onunhandledrejection","onunload","performance","stop","open","alert","confirm","prompt","print","requestAnimationFrame","cancelAnimationFrame","requestIdleCallback","cancelIdleCallback","captureEvents","releaseEvents","getComputedStyle","matchMedia","moveTo","moveBy","resizeTo","resizeBy","getSelection","find","webkitRequestAnimationFrame","webkitCancelAnimationFrame","fetch","btoa","atob","setTimeout","clearTimeout","setInterval","clearInterval","createImageBitmap","scroll","scrollTo","scrollBy","onappinstalled","onbeforeinstallprompt","crypto","ondevicemotion","ondeviceorientation","ondeviceorientationabsolute","indexedDB","webkitStorageInfo","sessionStorage","localStorage","chrome","visualViewport","speechSynthesis","webkitRequestFileSystem","webkitResolveLocalFileSystemURL","addEventListener", "removeEventListener", "openDatabase", "dispatchEvent", "onformdata", "onselectstart", "onselectionchange", "queueMicrotask", "onpointerrawupdate", "TEMPORARY", "PERSISTENT", "trustedTypes"]
if (navigator.userAgent.includes("Firefox")) {
	ks.push("onloadend"); ks.push("getDefaultComputedStyle"); ks.push("caches"); ks.push("InstallTrigger"); ks.push("aches"); ks.push("crossOriginIsolated"); ks.push("dump"); ks.push("event"); ks.push("fullScreen"); ks.push("getDefaultomputedStyle"); ks.push("mozInnerScreenX"); ks.push("mozInnerScreenY"); ks.push("onabsolutedeviceorientation"); ks.push("onanimationcancel"); ks.push("ondevicelight"); ks.push("ondragexit"); ks.push("ondragexit"); ks.push("onmozfullscreenchange"); ks.push("onmozfullscreenerror"); ks.push("onshow"); ks.push("ontransitioncancel"); ks.push("ondeviceproximity"); ks.push("ontransitionrun"); ks.push("ontransitionstart"); ks.push("onuserproximity"); ks.push("onvrdisplayactivate"); ks.push("onvrdisplayconnect"); ks.push("onvrdisplaydeactivate"); ks.push("onvrdisplaydeactivate"); ks.push("onvrdisplaydisconnect"); ks.push("onvrdisplaypresentchange"); ks.push("scrollByLines"); ks.push("scrollByPages"); ks.push("scrollMaxX"); ks.push("scrollMaxY"); ks.push("setResizable"); ks.push("sidebar"); ks.push("sizeToContent"); ks.push("updateCommands");
}
var prunedWindow = {}
for (let key in window) {
    if(ks.indexOf(key) == -1 && key !== "ks" && key !=="prunedWindow") {
        prunedWindow[key] = window[key]
    }
}
console.log(prunedWindow);
